### ISSUE TITLE
Git LFS Space

### ISSUE THREAD

**Issue by chrissexton** [IUS-CS/s20-project-jakob-drew-bryce-a-dog#15]
Hi all,

This repository happens to be using a bit of our Git LFS allotment and another active group is attempting to use the feature. Unfortunately GH doesn't really offer us much space in that regard so every megabyte counts. To that end, I may either commit a change that removes the LFS files here or just remove the repository. Would all of you mind forking your repository so that you have a copy of its assets?

Please leave me a comment here when you do or if you have other ideas. Thanks.

**Comment by bwwinne** [comment]
I have a backup so it's fine with me if you need to remove the repo.

**Comment by bwwinne** [comment]
I think Jakob and Drew will be fine with that as well

**Comment by chrissexton** [comment]
Thanks.
